---
- name: Install Slurm controller and necessary packages
  ansible.builtin.dnf:
    name:
      - munge
      - slurm
      - slurm-slurmdbd
      - slurm-libs
    state: present


#https://slurm.schedmd.com/quickstart_admin.html
#Controller: systemctl enable slurmctld
#Database: systemctl enable slurmdbd
#Compute Nodes: systemctl enable slurmd

- name: Start and enable Slurm services
  ansible.builtin.systemd:
    name: slurmdbd
    state: restarted
    enabled: true
