- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_distribution

- name: Remove software
  ansible.builtin.dnf:
    name: 
      - elisa
      - transmission
    state: absent
    autoremove: yes

- name: Install software
  ansible.builtin.dnf:
    name: 
     -  bridge-utils
      - chromium
      - curl
      - eza
      - dejavu-lgc-sans-fonts
      - gimp
      - libguestfs-tools
      - libvirt
      - okular
      - qbittorrent
      - qemu-kvm
      - terminator
      - thunderbird
      - virt-install
      - virt-manager
      - virt-viewer
      - virt-top
      - vlc
      - wget
      - wireshark
      - xauth

    state: latest
    update_cache: true

