---
- name: Make sure chronyd is installed
  ansible.builtin.apt:
    name: chrony
    state: latest
    update_cache: true

- name: Deploy chrony.conf template
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: "0644"
    backup: true

- name: Restart chronyd
  ansible.builtin.service:
    name: chronyd
    state: restarted
