---
- name: install chronyd - Make sure the clocks are synchronized across the cluster.
  ansible.builtin.yum:
    name: chrony
    state: latest
    update_cache: true

- name: Deploy chrony.conf template
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: "0644"
    backup: true

- name: Restart chronyd
  ansible.builtin.service:
    name: chronyd
    state: restarted
