---
- name: Add mappings to /etc/hosts
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  loop:
    - { name: submit.dundore.net, ip: 192.168.201.100 }
    - { name: compute1.dundore.net, ip: 192.168.201.101 }
    - { name: compute2.dundore.net, ip: 192.168.201.102 }
    - { name: slurmdb.dundore.net, ip: 192.168.201.99 }
