#add entries to hosts file
- blockinfile:
      state: present
      dest: etc_hosts
      content: |
        {% for host in groups.all %}
        submit.dundore.net 192.168.201.100
        compute1.dundore.net 192.168.201.101
        compute2.dundore.net 192.168.201.102
        slurmdb .dundore.net 192.168.201.99
        {% endfor %}