- name: Install chrony
  ansible.builtin.import_tasks: chrony.yml

- name: Update /etc/hosts file
  ansible.builtin.import_tasks: hosts.yml

- name: Install prerequisites
  ansible.builtin.import_tasks: prerequisites.yml

- name: Install ssh
  ansible.builtin.import_tasks: ssh.yml
