---
- name: SELinux
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: Make sure yum-utils is installed
  ansible.builtin.dnf:
    name: yum-utils
    state: latest

- name: clean dnf cache
  ansible.builtin.shell: dnf clean all 2>&1 >/dev/null

- name: install epel
  ansible.builtin.shell:  dnf config-manager --set-enabled crb && dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm 2>&1 >/dev/null

- name: clean dnf cache
  ansible.builtin.shell: dnf clean all 2>&1 >/dev/null

- name: Copy a new sudoers file into place, after passing validation with visudo
  ansible.builtin.template:
    src: 10_vagrant.j2
    dest: /etc/sudoers.d/10_vagrant
    validate: /usr/sbin/visudo -cf %s

  
