---
- name: Ensure group 'slurm' exists with correct gid
  ansible.builtin.group:
    name: slurm
    state: present
    gid: 1002
    
- name: Add the user 'slurm' with specific UID
  ansible.builtin.user:
    name: slurm
    comment: slurm application user
    uid: 1002
    group: slurm

- name: Creates directory
  ansible.builtin.file:
    path: /home/slurm/.ssh
    state: directory
    owner: slurm
    group: slurm
    mode: "0700"

- name: Copy ssh config into place for slurm
  ansible.builtin.template:
    src: config.j2
    dest: /home/slurm/.ssh/config
    owner: slurm
    group: slurm
    mode: "0600"
    backup: true


- name: Create Slurm directory if it does not exist
  file:
    path: /slurmctld
    state: directory
    mode: '0755'



- name: Create Slurm spool directory if it does not exist
  file:
    path: /slurmctld/spool
    state: directory
    mode: '0755'



- name: Install Slurm controller and necessary packages
  ansible.builtin.apt:
    name:
      - slurm
      - slurm-client
      - slurmctld
      - slurmd
      - slurmdbd
      - slurm-wlm
      - slurm-wlm-basic-plugins
    state: present

- name: Debug directory properties
  ansible.builtin.stat:
    path: /slurmctld
  register: dir_stat

- name: Show directory properties
  ansible.builtin.debug:
    msg:
      - "Owner: {{ dir_stat.stat.pw_name }}"
      - "Group: {{ dir_stat.stat.gr_name }}"
      - "Permissions: {{ dir_stat.stat.mode }}"

- name: Ensure /slurmctld ownership and permissions
  ansible.builtin.file:
    path: /slurmctld
    state: directory
    owner: slurm
    group: slurm
    mode: '0755'

- name: Debug directory properties
  ansible.builtin.stat:
    path: /slurmctld
  register: dir_stat

- name: Show directory properties
  ansible.builtin.debug:
    msg:
      - "Owner: {{ dir_stat.stat.pw_name }}"
      - "Group: {{ dir_stat.stat.gr_name }}"
      - "Permissions: {{ dir_stat.stat.mode }}"

- name: Debug directory properties
  ansible.builtin.stat:
    path: /slurmctld/spool
  register: dir_stat

- name: Show directory properties
  ansible.builtin.debug:
    msg:
      - "Owner: {{ dir_stat.stat.pw_name }}"
      - "Group: {{ dir_stat.stat.gr_name }}"
      - "Permissions: {{ dir_stat.stat.mode }}"

- name: Ensure /slurmctld/spool ownership and permissions
  ansible.builtin.file:
    path: /slurmctld/spool
    state: directory
    owner: slurm
    group: slurm
    mode: '0755'

- name: Debug directory properties
  ansible.builtin.stat:
    path: /slurmctld/spool
  register: dir_stat

- name: Show directory properties
  ansible.builtin.debug:
    msg:
      - "Owner: {{ dir_stat.stat.pw_name }}"
      - "Group: {{ dir_stat.stat.gr_name }}"
      - "Permissions: {{ dir_stat.stat.mode }}"

- name: Configure Slurm
  ansible.builtin.template:
    src: slurm.conf.j2
    dest: /etc/slurm/slurm.conf
  notify: restart slurm

- name: Start and enable Slurm services
  ansible.builtin.systemd:
    name: slurmctld
    state: started
    enabled: true