---
- name: clean dnf cache
  ansible.builtin.shell: dnf clean all 2>&1 >/dev/null

#- name: install openssh
#  ansible.builtin.dnf:
#    name:
#      - openssh-server
#      - openssh
#    state: latest

- name: Restart openssh
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Creates directory
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Creates directory
  ansible.builtin.file:
    path: /home/vagrant/.ssh
    state: directory
    owner: vagrant
    group: vagrant
    mode: "0700"

- name: Copy ssh config into place for vagrant
  ansible.builtin.template:
    src: config.j2
    dest: /home/vagrant/.ssh/config
    owner: vagrant
    group: vagrant
    mode: "0600"
    backup: true

- name: Copy ssh config into place for root
  ansible.builtin.template:
    src: config.j2
    dest: /root/.ssh/config
    owner: root
    group: root
    mode: "0600"
    backup: true

#Ensure hosts are in in the known_hosts file
- name: Fetch SSH keys from hosts
  ansible.builtin.command: ssh-keyscan -H {{ item }} 2>/dev/null
  register: ssh_keys
  loop:
    - submit.dundore.net
    - compute1.dundore.net
    - compute2.dundore.net
    - slurmdb.dundore.net

- name: Create temporary file with new keys
  ansible.builtin.copy:
    content: "{{ ssh_keys.results | map(attribute='stdout_lines') | sum(start=[]) | join('\n') }}"
    dest: /tmp/new_keys
    mode: "0644"

- name: Ensure known_hosts does not have duplicates
  ansible.builtin.shell: |
    sort -u /tmp/new_keys /root/.ssh/known_hosts | uniq > /tmp/known_hosts_temp
    cat /tmp/known_hosts_temp >> /root/.ssh/known_hosts
    cat /tmp/known_hosts_temp >> /home/vagrant/.ssh/known_hosts
  args:
    executable: /bin/bash

- name: Corrects permissions on the known_hosts file
  ansible.builtin.file:
    path: /home/vagrant/.ssh/known_hosts
    owner: vagrant
    group: vagrant
    mode: "0600"

- name: Corrects permissions on the known_hosts file
  ansible.builtin.file:
    path: /root/.ssh/known_hosts
    owner: root
    group: root
    mode: "0600"

- name: Clean up temporary file
  ansible.builtin.file:
    path: /tmp/new_keys
    state: absent
