---
- name: Deploy private key for vagrant
  ansible.builtin.template:
    src: id_rsa.j2
    dest: /home/vagrant/.ssh/id_rsa
    owner: vagrant
    group: vagrant
    mode: "0600"
    backup: true

- name: Set authorized key for vagrant taken from file
  ansible.posix.authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', '../templates/id_rsa.pub.j2') }}"

- name: Deploy private key for root
  ansible.builtin.template:
    src: id_rsa.j2
    dest: /root/.ssh/id_rsa
    owner: root
    group: root
    mode: "0600"
    backup: true

- name: Set authorized key for root taken from file
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '../templates/id_rsa.pub.j2') }}"