- name: Install Slurm compute node packages
     apt:
       name:
         - munge
         - libmunge2
         - libmunge-dev
       state: present

- name: Configure Slurm to point to the controller
      # Configuration details for the compute nodes to point to the controller should go here
