---
- name: Install NFS client package
  dnf:
    name: nfs-utils
    state: present

- name: Ensure /mnt/nfs/home exists
  ansible.builtin.file:
    path: /mnt/nfs/home
    state: directory
    mode: '0777'

- name: Ensure /mnt/nfs/scripts exists
  ansible.builtin.file:
    path: /mnt/nfs/scripts
    state: directory
    mode: '0777'

- name: Mount scripts NFS share
  mount:
    path: /mnt/nfs/scripts
    src: "submit.dundore.net:/vagrant/scripts"
    fstype: nfs
    state: mounted
    opts: rw,vers=3,hard,intr

- name: Ensure scripts NFS share is mounted on boot
  mount:
    path: /mnt/nfs/scripts
    src: "submit.dundore.net:/vagrant/scripts"
    fstype: nfs
    opts: rw,vers=3,hard,intr
    state: mounted

- name: Mount home NFS share
  mount:
    path: /mnt/nfs/home
    src: "submit.dundore.net:/mnt/nfs/home"
    fstype: nfs
    state: mounted
    opts: rw,vers=3,hard,intr

- name: Ensure home NFS share is mounted on boot
  mount:
    path: /mnt/nfs/home
    src: "submit.dundore.net:/mnt/nfs/home"
    fstype: nfs
    opts: rw,vers=3,hard,intr
    state: mounted

- name: Reload systemd manager configuration
  ansible.builtin.systemd:
    daemon_reload: yes

