- name: Install Slurm controller and necessary packages
  ansible.builtin.dnf:
    name:
      - slurm
      - slurm-slurmd
      - slurm-perlapi
    state: present

- name: Ensure slurmd is running as slurm user
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/slurmd.service
    regexp: '^User='
    line: 'User=slurm'
  notify: Restart slurmd

- name: Ensure slurmd group is correct
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/slurmd.service
    regexp: '^Group='
    line: 'Group=slurm'
  notify: Restart slurmd

- name: Start and enable Slurm services
  ansible.builtin.systemd:
    name: slurmd
    state: restarted
    enabled: true

- name: Reboot the node
  reboot:
    msg: "Rebooting to apply updates and recheck memory configuration."
    pre_reboot_delay: 5
    post_reboot_delay: 60
    test_command: whoami

- name: Start and enable munge
  ansible.builtin.systemd:
    name: munge
    state: restarted
    enabled: true

- name: Start and enable Slurm services
  ansible.builtin.systemd:
    name: slurmd
    state: restarted
    enabled: true