---
- name: Install Slurm controller and necessary packages
  ansible.builtin.apt:
    name:
      - slurm
      - slurm-client
      - slurmd
      - slurm-wlm
      - slurm-wlm-basic-plugins
    state: present
