- name: Ensure group 'slurm' exists with correct gid
  ansible.builtin.group:
    name: slurm
    state: present
    gid: 1002

- name: Add the user 'slurm' with specific UID
  ansible.builtin.user:
    name: slurm
    comment: slurm application user
    uid: 1002
    group: slurm
    state: present

- name: Create Slurm directories if they do not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: slurm
    group: slurm
    mode: '0755'
  loop:
    - /var/run/slurm
    - /var/log/slurm
    - /slurmctld
    - /slurmctld/spool

- name: Install Slurm controller and necessary packages
  ansible.builtin.dnf:
    name:
      - slurm
      - slurm-slurmd
      - slurm-perlapi
    state: present

- name: Ensure slurmd is running as slurm user
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/slurmd.service
    regexp: '^User='
    line: 'User=slurm'
  notify: Restart slurmd

- name: Ensure slurmd group is correct
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/slurmd.service
    regexp: '^Group='
    line: 'Group=slurm'
  notify: Restart slurmd

- name: Configure Slurm
  ansible.builtin.template:
    src: slurm.conf.j2
    dest: /etc/slurm/slurm.conf

- name: Configure cgroup for Slurm
  ansible.builtin.template:
    src: cgroup.conf.j2
    dest: /etc/slurm/cgroup.conf

- name: Start and enable Slurm services
  ansible.builtin.systemd:
    name: slurmd
    state: restarted
    enabled: true