---
- name: Ensure group 'munge' exists with correct gid
  ansible.builtin.group:
    name: munge
    state: present
    gid: 1001

- name: Add the user 'munge' with specific UID
  ansible.builtin.user:
    name: munge
    comment: munge application user
    uid: 1001
    group: munge
    shell: /bin/no-login

- name: Creates directory
  ansible.builtin.file:
    path: /home/munge/.ssh
    state: directory
    owner: munge
    group: munge
    mode: "0700"

- name: Copy ssh config into place for munge
  ansible.builtin.template:
    src: config.j2
    dest: /home/munge/.ssh/config
    owner: munge
    group: munge
    mode: "0600"
    backup: true

- name: Install munge
  ansible.builtin.apt:
    name:
      - munge
      - libmunge2
      - libmunge-dev
    state: present

- name: Change permissions to 0700 for munge
  ansible.builtin.file:
    path:
      - /etc/munge
      - /var/log/munge
      - /var/lib/munge
    state: directory
    owner: munge
    group: munge
    mode: "0700"

- name: Change permissions to 0755 for munge
  ansible.builtin.file:
    path:
      - /run/munge
    state: directory
    owner: munge
    group: munge
    mode: "0755"

- name: Deploy munge key
  ansible.builtin.template:
    src: munge.key.j2
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: '0700'
  notify: restart munge

- name: Start Munge service
  ansible.builtin.service:
    name: munge
    state: restarted
  register: munge_installed
  ignore_errors: true
