---
 
- name: Install munge
  ansible.builtin.dnf:
    name:
        - munge
        - libmunge2
        - libmunge-dev
    state: present
 
- name: Start Munge service
  service: name=munge state=started
  register: munge_installed
  ignore_errors: yes
