---
- name: Ensure group 'slurm' exists with correct gid
  ansible.builtin.group:
    name: slurm
    state: present
    gid: 1002
    
- name: Add the user 'slurm' with specific UID
  ansible.builtin.user:
    name: slurm
    comment: slurm application user
    uid: 1002
    group: slurm

#- name: Run a command as the slurm user
#  command: somecommand
#  become: true
#  become_user: slurm

- name: Create Slurm directory if it does not exist
  file:
    path: /slurmctld
    state: directory
    mode: '0755'

- name: Create Slurm state directory if it does not exist
  file:
    path: /slurmctld/state
    state: directory
    mode: '0755'

- name: Create Slurm spool directory if it does not exist
  file:
    path: /slurmctld/spool
    state: directory
    mode: '0755'

- name: Debug directory properties
  ansible.builtin.stat:
    path: /slurmctld
  register: dir_stat

- name: Install Slurm controller and necessary packages
  ansible.builtin.dnf:
    name:
      - slurm
      - slurm-perlapi
      - slurm-slurmctld
      - slurm-slurmd
      - slurm-libs
    state: present


- name: Show directory properties
  ansible.builtin.debug:
    msg:
      - "Owner: {{ dir_stat.stat.pw_name }}"
      - "Group: {{ dir_stat.stat.gr_name }}"
      - "Permissions: {{ dir_stat.stat.mode }}"

- name: Ensure /slurmctld ownership and permissions
  ansible.builtin.file:
    path: /slurmctld
    state: directory
    owner: slurm
    group: slurm
    mode: '0755'

- name: Debug directory properties
  ansible.builtin.stat:
    path: /slurmctld
  register: dir_stat

- name: Show directory properties
  ansible.builtin.debug:
    msg:
      - "Owner: {{ dir_stat.stat.pw_name }}"
      - "Group: {{ dir_stat.stat.gr_name }}"
      - "Permissions: {{ dir_stat.stat.mode }}"

- name: Debug directory properties
  ansible.builtin.stat:
    path: /slurmctld/spool
  register: dir_stat

- name: Show directory properties
  ansible.builtin.debug:
    msg:
      - "Owner: {{ dir_stat.stat.pw_name }}"
      - "Group: {{ dir_stat.stat.gr_name }}"
      - "Permissions: {{ dir_stat.stat.mode }}"

- name: Ensure /slurmctld/spool ownership and permissions
  ansible.builtin.file:
    path: /slurmctld/spool
    state: directory
    owner: slurm
    group: slurm
    mode: '0755'

- name: Debug directory properties
  ansible.builtin.stat:
    path: /slurmctld/spool
  register: dir_stat

- name: Show directory properties
  ansible.builtin.debug:
    msg:
      - "Owner: {{ dir_stat.stat.pw_name }}"
      - "Group: {{ dir_stat.stat.gr_name }}"
      - "Permissions: {{ dir_stat.stat.mode }}"

- name: Configure Slurm
  ansible.builtin.template:
    src: slurm.conf.j2
    dest: /etc/slurm/slurm.conf
  notify: restart slurm

#https://slurm.schedmd.com/quickstart_admin.html
#Controller: systemctl enable slurmctld
#Database: systemctl enable slurmdbd
#Compute Nodes: systemctl enable slurmd
- name: Start and enable Slurm services
  ansible.builtin.systemd:
    name: slurmctld
    state: restarted
    enabled: true

- name: scontrol reconfig cmd after slurm installation
  ansible.builtin.shell:
    cmd: "scontrol reconfig"

#- name: attempt to start node compute1
#  ansible.builtin.shell:
#    cmd: scontrol update NodeName=compute1 State=resume > /dev/null 2>&1
#  args:
#    executable: /bin/bash

#- name: attempt to start node compute2
#  ansible.builtin.shell:
#    cmd: scontrol update NodeName=compute2 State=resume > /dev/null 2>&1
#  args:
#    executable: /bin/bash

