---
- name: Install Slurm controller and necessary packages
  ansible.builtin.dnf:
    name:
      - slurm
      - slurm-perlapi
      - slurm-slurmctld
      - slurm-libs
    state: present


#https://slurm.schedmd.com/quickstart_admin.html
#Controller: systemctl enable slurmctld
#Database: systemctl enable slurmdbd
#Compute Nodes: systemctl enable slurmd
- name: Start and enable Slurm services
  ansible.builtin.systemd:
    name: slurmctld
    state: restarted
    enabled: true

- name: scontrol reconfig cmd after slurm installation
  ansible.builtin.shell:
    cmd: "scontrol reconfig"

- name: Start and enable Slurm services
  ansible.builtin.systemd:
    name: slurmctld
    state: restarted
    enabled: true
