---
- name: restart slurmctl
  ansible.builtin.systemd:
    name: slurmctld
    state: restarted

- name: Restart slurmd
  ansible.builtin.systemd:
    name: slurmd
    state: restarted

- name: restart munge
  ansible.builtin.systemd:
    name: munge
    state: restarted