[slurm_controller]
submit.dundore.net ansible_ssh_user=vagrant

[compute_node]
compute1.dundore.net ansible_ssh_user=vagrant
compute2.dundore.net ansible_ssh_user=vagrant

[slurm_controller:vars]
slurm_controller_hostname = submit.dundore.net
slurm_controller_address = 192.168.1.1