[slurm_controller]
submit.dundore.net

[compute_node]
compute1.dundore.net
compute2.dundore.net

[slurmdb]
slurmdb.dundore.net

[slurm_controller:vars]
slurm_controller_hostname = submit.dundore.net
slurm_controller_address = 192.168.201.100

[all:vars]
ansible_python_interpreter=/usr/bin/python3